2023-05-03 09:10:27,699 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.92:34075'
2023-05-03 09:10:32,030 - distributed.worker - INFO -       Start worker at:    tcp://172.16.3.92:41350
2023-05-03 09:10:32,030 - distributed.worker - INFO -          Listening to:    tcp://172.16.3.92:41350
2023-05-03 09:10:32,030 - distributed.worker - INFO -           Worker name:             SLURMCluster-3
2023-05-03 09:10:32,030 - distributed.worker - INFO -          dashboard at:          172.16.3.92:38481
2023-05-03 09:10:32,030 - distributed.worker - INFO - Waiting to connect to:   tcp://172.16.3.158:34390
2023-05-03 09:10:32,030 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 09:10:32,030 - distributed.worker - INFO -               Threads:                         36
2023-05-03 09:10:32,030 - distributed.worker - INFO -                Memory:                  93.13 GiB
2023-05-03 09:10:32,030 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-p5ink2fg
2023-05-03 09:10:32,030 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 09:10:32,035 - distributed.worker - INFO -         Registered to:   tcp://172.16.3.158:34390
2023-05-03 09:10:32,036 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 09:10:32,036 - distributed.core - INFO - Starting established connection to tcp://172.16.3.158:34390
2023-05-03 09:13:08,895 - distributed.utils_perf - INFO - full garbage collection released 3.84 GiB from 440 reference cycles (threshold: 9.54 MiB)
2023-05-03 09:13:17,106 - distributed.utils_perf - INFO - full garbage collection released 1.74 GiB from 300 reference cycles (threshold: 9.54 MiB)
2023-05-03 09:13:28,841 - distributed.core - INFO - Removing comms to tcp://172.16.3.105:34566
2023-05-03 09:13:31,899 - distributed.utils_perf - INFO - full garbage collection released 832.48 MiB from 180 reference cycles (threshold: 9.54 MiB)
2023-05-03 09:13:39,114 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.76s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-05-03 09:13:48,658 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.88:43865
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 317, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2891, in get_data_from_worker
    response = await send_recv(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1025, in send_recv
    await comm.write(msg, serializers=serializers, on_error="raise")
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 328, in write
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://172.16.3.92:59433 remote=tcp://172.16.3.88:43865>: Stream is closed
2023-05-03 09:13:49,689 - distributed.core - INFO - Removing comms to tcp://172.16.3.88:43865
2023-05-03 09:13:57,293 - distributed.worker.memory - WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 74.56 GiB -- Worker memory limit: 93.13 GiB
2023-05-03 09:13:57,642 - distributed.worker.memory - WARNING - Worker is at 77% memory usage. Resuming worker. Process memory: 71.98 GiB -- Worker memory limit: 93.13 GiB
2023-05-03 09:13:58,058 - distributed.worker.memory - WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 74.67 GiB -- Worker memory limit: 93.13 GiB
2023-05-03 09:13:58,505 - distributed.worker.memory - WARNING - Worker is at 78% memory usage. Resuming worker. Process memory: 73.41 GiB -- Worker memory limit: 93.13 GiB
2023-05-03 09:13:58,713 - distributed.worker.memory - WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 74.77 GiB -- Worker memory limit: 93.13 GiB
2023-05-03 09:13:59,441 - distributed.worker.memory - WARNING - Worker is at 76% memory usage. Resuming worker. Process memory: 71.67 GiB -- Worker memory limit: 93.13 GiB
2023-05-03 09:14:13,145 - distributed.nanny.memory - WARNING - Worker tcp://172.16.3.92:41350 (pid=287750) exceeded 95% memory budget. Restarting...
2023-05-03 09:14:19,796 - distributed.nanny - INFO - Worker process 287750 was killed by signal 15
2023-05-03 09:14:30,574 - distributed.nanny - WARNING - Restarting worker
2023-05-03 09:14:35,358 - distributed.worker - INFO -       Start worker at:    tcp://172.16.3.92:40929
2023-05-03 09:14:35,358 - distributed.worker - INFO -          Listening to:    tcp://172.16.3.92:40929
2023-05-03 09:14:35,358 - distributed.worker - INFO -           Worker name:             SLURMCluster-3
2023-05-03 09:14:35,358 - distributed.worker - INFO -          dashboard at:          172.16.3.92:45902
2023-05-03 09:14:35,358 - distributed.worker - INFO - Waiting to connect to:   tcp://172.16.3.158:34390
2023-05-03 09:14:35,358 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 09:14:35,358 - distributed.worker - INFO -               Threads:                         36
2023-05-03 09:14:35,358 - distributed.worker - INFO -                Memory:                  93.13 GiB
2023-05-03 09:14:35,358 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-eu9ityz6
2023-05-03 09:14:35,358 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 09:15:05,359 - distributed.worker - INFO - Waiting to connect to:   tcp://172.16.3.158:34390
2023-05-03 09:15:30,576 - distributed.nanny - ERROR - Timed out connecting Nanny '<Nanny: tcp://172.16.3.92:41350, threads: 36>' to scheduler 'tcp://172.16.3.158:34390'
2023-05-03 09:15:30,576 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.16.3.92:34075'. Reason: nanny-instantiate-timeout
2023-05-03 09:15:32,671 - distributed.worker - INFO - Stopping worker at tcp://172.16.3.92:40929. Reason: worker-close
2023-05-03 09:15:32,671 - distributed.worker - INFO - Closed worker has not yet started: Status.init
2023-05-03 09:15:32,674 - distributed.nanny - ERROR - Failed to start worker
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/core.py", line 292, in connect
    comm = await wait_for(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils.py", line 1850, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 511, in connect
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x2aaacafcef80>: ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 1472, in start_unsafe
    await self._register_with_scheduler()
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 1163, in _register_with_scheduler
    comm = await connect(self.scheduler.address, **self.connection_args)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/core.py", line 316, in connect
    await asyncio.sleep(backoff)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 537, in start
    await wait_for(self.start_unsafe(), timeout=timeout)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils.py", line 1850, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/nanny.py", line 930, in run
    async with worker:
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 550, in __aenter__
    await self
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 540, in start
    raise asyncio.TimeoutError(
asyncio.exceptions.TimeoutError: Worker start timed out after 60s.
2023-05-03 09:15:34,898 - distributed.nanny - ERROR - Worker process died unexpectedly
slurmstepd: error: *** JOB 3082087 ON pn042 CANCELLED AT 2023-05-03T11:10:37 DUE TO TIME LIMIT ***
