2023-05-02 19:27:32,908 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.88:39637'
2023-05-02 19:27:41,651 - distributed.worker - INFO -       Start worker at:    tcp://172.16.3.88:33521
2023-05-02 19:27:41,651 - distributed.worker - INFO -          Listening to:    tcp://172.16.3.88:33521
2023-05-02 19:27:41,651 - distributed.worker - INFO -           Worker name:             SLURMCluster-3
2023-05-02 19:27:41,651 - distributed.worker - INFO -          dashboard at:          172.16.3.88:39632
2023-05-02 19:27:41,651 - distributed.worker - INFO - Waiting to connect to:   tcp://172.16.3.106:34537
2023-05-02 19:27:41,651 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 19:27:41,651 - distributed.worker - INFO -               Threads:                         36
2023-05-02 19:27:41,652 - distributed.worker - INFO -                Memory:                  93.13 GiB
2023-05-02 19:27:41,652 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-in4c2jhe
2023-05-02 19:27:41,652 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 19:27:41,658 - distributed.worker - INFO -         Registered to:   tcp://172.16.3.106:34537
2023-05-02 19:27:41,658 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 19:27:41,658 - distributed.core - INFO - Starting established connection to tcp://172.16.3.106:34537
2023-05-02 19:28:03,041 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.00s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-05-02 19:29:51,184 - distributed.core - INFO - Connection to tcp://172.16.3.106:34537 has been closed.
2023-05-02 19:29:51,186 - distributed.worker - INFO - Stopping worker at tcp://172.16.3.88:33521. Reason: worker-handle-scheduler-connection-broken
2023-05-02 19:29:51,188 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 1234, in heartbeat
    response = await retry_operation(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1268, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.16.3.88:48304 remote=tcp://172.16.3.106:34537>: ConnectionResetError: [Errno 104] Connection reset by peer
2023-05-02 19:29:51,260 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.16.3.88:39637'. Reason: worker-handle-scheduler-connection-broken
2023-05-02 19:30:21,660 - distributed.nanny - INFO - Worker closed
2023-05-02 19:30:24,068 - distributed.nanny - ERROR - Worker process died unexpectedly
2023-05-02 19:32:11,069 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.16.3.88:39637'. Reason: nanny-close-gracefully
2023-05-02 19:32:11,070 - distributed.dask_worker - INFO - End worker
