2023-05-03 09:51:35,302 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.93:40384'
2023-05-03 09:51:37,816 - distributed.worker - INFO -       Start worker at:    tcp://172.16.3.93:44596
2023-05-03 09:51:37,817 - distributed.worker - INFO -          Listening to:    tcp://172.16.3.93:44596
2023-05-03 09:51:37,817 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2023-05-03 09:51:37,817 - distributed.worker - INFO -          dashboard at:          172.16.3.93:42384
2023-05-03 09:51:37,817 - distributed.worker - INFO - Waiting to connect to:   tcp://172.16.3.158:45398
2023-05-03 09:51:37,817 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 09:51:37,817 - distributed.worker - INFO -               Threads:                         36
2023-05-03 09:51:37,817 - distributed.worker - INFO -                Memory:                 178.81 GiB
2023-05-03 09:51:37,817 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-33u0m4ug
2023-05-03 09:51:37,817 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 09:51:37,864 - distributed.worker - INFO -         Registered to:   tcp://172.16.3.158:45398
2023-05-03 09:51:37,864 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 09:51:37,865 - distributed.core - INFO - Starting established connection to tcp://172.16.3.158:45398
2023-05-03 09:51:53,342 - distributed.utils_perf - INFO - full garbage collection released 162.29 MiB from 180 reference cycles (threshold: 9.54 MiB)
2023-05-03 09:54:42,804 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.189:41839
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2891, in get_data_from_worker
    response = await send_recv(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://172.16.3.93:53625 remote=tcp://172.16.3.189:41839>: Stream is closed
2023-05-03 09:54:42,827 - distributed.core - INFO - Removing comms to tcp://172.16.3.189:41839
2023-05-03 09:55:33,177 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.168:42978
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2891, in get_data_from_worker
    response = await send_recv(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://172.16.3.93:34618 remote=tcp://172.16.3.168:42978>: Stream is closed
2023-05-03 09:55:33,215 - distributed.core - INFO - Removing comms to tcp://172.16.3.168:42978
2023-05-03 10:03:28,728 - distributed.core - INFO - Removing comms to tcp://172.16.3.88:39818
2023-05-03 10:03:28,730 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.88:39818
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2891, in get_data_from_worker
    response = await send_recv(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://172.16.3.93:37823 remote=tcp://172.16.3.88:39818>: Stream is closed
2023-05-03 10:05:41,878 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.190:41909
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2891, in get_data_from_worker
    response = await send_recv(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://172.16.3.93:56949 remote=tcp://172.16.3.190:41909>: Stream is closed
2023-05-03 10:05:42,311 - distributed.core - INFO - Removing comms to tcp://172.16.3.190:41909
2023-05-03 10:08:33,311 - distributed.core - INFO - Removing comms to tcp://172.16.3.63:37036
2023-05-03 10:08:33,311 - distributed.core - INFO - Removing comms to tcp://172.16.3.62:43664
2023-05-03 10:08:33,346 - distributed.core - INFO - Removing comms to tcp://172.16.3.61:36881
2023-05-03 10:08:33,385 - distributed.core - INFO - Removing comms to tcp://172.16.3.167:41945
slurmstepd: error: *** JOB 3082144 ON pn043 CANCELLED AT 2023-05-03T10:08:33 ***
