2023-05-10 08:37:53,994 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.101:35367'
2023-05-10 08:38:01,992 - distributed.worker - INFO -       Start worker at:   tcp://172.16.3.101:33924
2023-05-10 08:38:01,992 - distributed.worker - INFO -          Listening to:   tcp://172.16.3.101:33924
2023-05-10 08:38:01,992 - distributed.worker - INFO -           Worker name:             SLURMCluster-6
2023-05-10 08:38:01,992 - distributed.worker - INFO -          dashboard at:         172.16.3.101:45693
2023-05-10 08:38:01,992 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.56:37266
2023-05-10 08:38:01,992 - distributed.worker - INFO - -------------------------------------------------
2023-05-10 08:38:01,992 - distributed.worker - INFO -               Threads:                         30
2023-05-10 08:38:01,992 - distributed.worker - INFO -                Memory:                  46.57 GiB
2023-05-10 08:38:01,992 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-2a8dkp70
2023-05-10 08:38:01,992 - distributed.worker - INFO - -------------------------------------------------
2023-05-10 08:38:02,000 - distributed.worker - INFO -         Registered to:    tcp://172.16.3.56:37266
2023-05-10 08:38:02,000 - distributed.worker - INFO - -------------------------------------------------
2023-05-10 08:38:02,000 - distributed.core - INFO - Starting established connection to tcp://172.16.3.56:37266
Exception ignored in: <function CachingFileManager.__del__ at 0x2aaacb7ff6d0>
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 249, in __del__
    self.close(needs_lock=False)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 233, in close
    file.close()
  File "src/netCDF4/_netCDF4.pyx", line 2607, in netCDF4._netCDF4.Dataset.close
  File "src/netCDF4/_netCDF4.pyx", line 2570, in netCDF4._netCDF4.Dataset._close
  File "src/netCDF4/_netCDF4.pyx", line 2014, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID
Exception ignored in: <function CachingFileManager.__del__ at 0x2aaacb7ff6d0>
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 249, in __del__
    self.close(needs_lock=False)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 233, in close
    file.close()
  File "src/netCDF4/_netCDF4.pyx", line 2607, in netCDF4._netCDF4.Dataset.close
  File "src/netCDF4/_netCDF4.pyx", line 2570, in netCDF4._netCDF4.Dataset._close
  File "src/netCDF4/_netCDF4.pyx", line 2014, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID
Exception ignored in: <function CachingFileManager.__del__ at 0x2aaacb7ff6d0>
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 249, in __del__
    self.close(needs_lock=False)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 233, in close
    file.close()
  File "src/netCDF4/_netCDF4.pyx", line 2607, in netCDF4._netCDF4.Dataset.close
  File "src/netCDF4/_netCDF4.pyx", line 2570, in netCDF4._netCDF4.Dataset._close
  File "src/netCDF4/_netCDF4.pyx", line 2014, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID
Exception ignored in: <function CachingFileManager.__del__ at 0x2aaacb7ff6d0>
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 249, in __del__
    self.close(needs_lock=False)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 233, in close
    file.close()
  File "src/netCDF4/_netCDF4.pyx", line 2607, in netCDF4._netCDF4.Dataset.close
  File "src/netCDF4/_netCDF4.pyx", line 2570, in netCDF4._netCDF4.Dataset._close
  File "src/netCDF4/_netCDF4.pyx", line 2014, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID
2023-05-10 08:42:22,711 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 32.73 GiB -- Worker memory limit: 46.57 GiB
2023-05-10 08:42:23,463 - distributed.worker.memory - WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 37.34 GiB -- Worker memory limit: 46.57 GiB
2023-05-10 08:42:23,974 - distributed.worker.memory - WARNING - Worker is at 75% memory usage. Resuming worker. Process memory: 35.25 GiB -- Worker memory limit: 46.57 GiB
2023-05-10 08:42:24,201 - distributed.worker.memory - WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 37.57 GiB -- Worker memory limit: 46.57 GiB
2023-05-10 08:42:25,876 - distributed.worker.memory - WARNING - Worker is at 77% memory usage. Resuming worker. Process memory: 36.32 GiB -- Worker memory limit: 46.57 GiB
2023-05-10 08:42:26,001 - distributed.worker.memory - WARNING - Worker is at 82% memory usage. Pausing worker.  Process memory: 38.39 GiB -- Worker memory limit: 46.57 GiB
2023-05-10 08:42:26,933 - distributed.worker.memory - WARNING - Worker is at 75% memory usage. Resuming worker. Process memory: 35.23 GiB -- Worker memory limit: 46.57 GiB
2023-05-10 08:42:32,592 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.59s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-05-10 08:42:35,160 - distributed.core - INFO - Removing comms to tcp://172.16.3.185:33858
2023-05-10 08:42:35,281 - distributed.core - INFO - Removing comms to tcp://172.16.3.128:37079
2023-05-10 08:42:35,282 - distributed.core - INFO - Removing comms to tcp://172.16.3.129:43962
2023-05-10 08:42:37,327 - distributed.nanny.memory - WARNING - Worker tcp://172.16.3.101:33924 (pid=304951) exceeded 95% memory budget. Restarting...
2023-05-10 08:42:37,427 - distributed.nanny.memory - WARNING - Worker tcp://172.16.3.101:33924 (pid=304951) is slow to accept SIGTERM; sending SIGKILL
2023-05-10 08:42:42,457 - distributed.nanny - INFO - Worker process 304951 was killed by signal 15
2023-05-10 08:42:45,827 - distributed.nanny - WARNING - Restarting worker
2023-05-10 08:42:50,104 - distributed.worker - INFO -       Start worker at:   tcp://172.16.3.101:40522
2023-05-10 08:42:50,106 - distributed.worker - INFO -          Listening to:   tcp://172.16.3.101:40522
2023-05-10 08:42:50,106 - distributed.worker - INFO -           Worker name:             SLURMCluster-6
2023-05-10 08:42:50,106 - distributed.worker - INFO -          dashboard at:         172.16.3.101:46055
2023-05-10 08:42:50,106 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.56:37266
2023-05-10 08:42:50,106 - distributed.worker - INFO - -------------------------------------------------
2023-05-10 08:42:50,106 - distributed.worker - INFO -               Threads:                         30
2023-05-10 08:42:50,106 - distributed.worker - INFO -                Memory:                  46.57 GiB
2023-05-10 08:42:50,106 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-jbib_qhl
2023-05-10 08:42:50,106 - distributed.worker - INFO - -------------------------------------------------
2023-05-10 08:42:50,115 - distributed.worker - INFO -         Registered to:    tcp://172.16.3.56:37266
2023-05-10 08:42:50,115 - distributed.worker - INFO - -------------------------------------------------
2023-05-10 08:42:50,116 - distributed.core - INFO - Starting established connection to tcp://172.16.3.56:37266
slurmstepd: error: *** JOB 3085330 ON pn051 CANCELLED AT 2023-05-10T08:42:50 ***
