2023-05-03 10:26:24,657 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.167:35745'
2023-05-03 10:26:25,972 - distributed.worker - INFO -       Start worker at:   tcp://172.16.3.167:36822
2023-05-03 10:26:25,972 - distributed.worker - INFO -          Listening to:   tcp://172.16.3.167:36822
2023-05-03 10:26:25,972 - distributed.worker - INFO -           Worker name:            SLURMCluster-10
2023-05-03 10:26:25,972 - distributed.worker - INFO -          dashboard at:         172.16.3.167:39120
2023-05-03 10:26:25,972 - distributed.worker - INFO - Waiting to connect to:   tcp://172.16.3.158:44860
2023-05-03 10:26:25,973 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 10:26:25,973 - distributed.worker - INFO -               Threads:                         36
2023-05-03 10:26:25,973 - distributed.worker - INFO -                Memory:                 178.81 GiB
2023-05-03 10:26:25,973 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-8dg9fcn3
2023-05-03 10:26:25,973 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 10:26:25,978 - distributed.worker - INFO -         Registered to:   tcp://172.16.3.158:44860
2023-05-03 10:26:25,978 - distributed.worker - INFO - -------------------------------------------------
2023-05-03 10:26:25,979 - distributed.core - INFO - Starting established connection to tcp://172.16.3.158:44860
2023-05-03 10:35:15,340 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 1234, in heartbeat
    response = await retry_operation(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1268, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.16.3.167:40422 remote=tcp://172.16.3.158:44860>: ConnectionResetError: [Errno 104] Connection reset by peer
2023-05-03 10:35:15,344 - distributed.core - INFO - Connection to tcp://172.16.3.158:44860 has been closed.
2023-05-03 10:35:15,344 - distributed.worker - INFO - Stopping worker at tcp://172.16.3.167:36822. Reason: worker-handle-scheduler-connection-broken
2023-05-03 10:35:15,348 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.16.3.167:35745'. Reason: worker-handle-scheduler-connection-broken
2023-05-03 10:35:45,353 - distributed.nanny - INFO - Worker closed
2023-05-03 10:37:36,120 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.16.3.167:35745'. Reason: nanny-close-gracefully
2023-05-03 10:37:36,121 - distributed.dask_worker - INFO - End worker
