2023-04-17 15:53:39,404 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.95:36651'
2023-04-17 15:54:02,469 - distributed.worker - INFO -       Start worker at:    tcp://172.16.3.95:38125
2023-04-17 15:54:02,469 - distributed.worker - INFO -          Listening to:    tcp://172.16.3.95:38125
2023-04-17 15:54:02,469 - distributed.worker - INFO -           Worker name:             SLURMCluster-2
2023-04-17 15:54:02,469 - distributed.worker - INFO -          dashboard at:          172.16.3.95:44080
2023-04-17 15:54:02,469 - distributed.worker - INFO - Waiting to connect to:   tcp://172.16.3.167:35988
2023-04-17 15:54:02,469 - distributed.worker - INFO - -------------------------------------------------
2023-04-17 15:54:02,469 - distributed.worker - INFO -               Threads:                         36
2023-04-17 15:54:02,469 - distributed.worker - INFO -                Memory:                 178.81 GiB
2023-04-17 15:54:02,469 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-lz935nou
2023-04-17 15:54:02,469 - distributed.worker - INFO - -------------------------------------------------
2023-04-17 15:54:02,490 - distributed.worker - INFO -         Registered to:   tcp://172.16.3.167:35988
2023-04-17 15:54:02,491 - distributed.worker - INFO - -------------------------------------------------
2023-04-17 15:54:02,491 - distributed.core - INFO - Starting established connection to tcp://172.16.3.167:35988
2023-04-17 15:54:08,563 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.07s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-17 16:10:31,817 - distributed.core - INFO - Event loop was unresponsive in Worker for 10.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-17 17:24:43,798 - distributed.utils_perf - INFO - full garbage collection released 12.13 MiB from 11217 reference cycles (threshold: 9.54 MiB)
2023-04-17 17:32:05,454 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/tornado/iostream.py", line 867, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/tornado/iostream.py", line 1140, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/worker.py", line 1215, in heartbeat
    response = await retry_operation(
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/utils_comm.py", line 386, in retry_operation
    return await retry(
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/utils_comm.py", line 371, in retry
    return await coro()
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/core.py", line 1163, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/core.py", line 928, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.16.3.95:45680 remote=tcp://172.16.3.167:35988>: ConnectionResetError: [Errno 104] Connection reset by peer
2023-04-17 17:32:05,700 - distributed.core - INFO - Connection to tcp://172.16.3.167:35988 has been closed.
2023-04-17 17:32:05,700 - distributed.worker - INFO - Stopping worker at tcp://172.16.3.95:38125. Reason: worker-handle-scheduler-connection-broken
2023-04-17 17:32:05,702 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.16.3.95:36651'. Reason: worker-handle-scheduler-connection-broken
2023-04-17 17:32:05,706 - distributed.nanny - INFO - Worker closed
2023-04-17 17:32:11,077 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.16.3.95:36651'. Reason: nanny-close-gracefully
2023-04-17 17:32:11,077 - distributed.dask_worker - INFO - End worker
