2023-05-02 23:41:46,935 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.90:45045'
2023-05-02 23:42:06,968 - distributed.worker - INFO -       Start worker at:    tcp://172.16.3.90:41382
2023-05-02 23:42:06,968 - distributed.worker - INFO -          Listening to:    tcp://172.16.3.90:41382
2023-05-02 23:42:06,968 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2023-05-02 23:42:06,968 - distributed.worker - INFO -          dashboard at:          172.16.3.90:41108
2023-05-02 23:42:06,968 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.60:33052
2023-05-02 23:42:06,968 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 23:42:06,968 - distributed.worker - INFO -               Threads:                         36
2023-05-02 23:42:06,968 - distributed.worker - INFO -                Memory:                  93.13 GiB
2023-05-02 23:42:06,968 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-bmcf5dae
2023-05-02 23:42:06,968 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 23:42:06,974 - distributed.worker - INFO -         Registered to:    tcp://172.16.3.60:33052
2023-05-02 23:42:06,974 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 23:42:06,974 - distributed.core - INFO - Starting established connection to tcp://172.16.3.60:33052
2023-05-02 23:44:11,605 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 1234, in heartbeat
    response = await retry_operation(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1268, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.16.3.90:39297 remote=tcp://172.16.3.60:33052>: ConnectionResetError: [Errno 104] Connection reset by peer
2023-05-02 23:44:11,651 - distributed.core - INFO - Connection to tcp://172.16.3.60:33052 has been closed.
2023-05-02 23:44:11,651 - distributed.worker - INFO - Stopping worker at tcp://172.16.3.90:41382. Reason: worker-handle-scheduler-connection-broken
2023-05-02 23:44:11,653 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.16.3.90:45045'. Reason: worker-handle-scheduler-connection-broken
2023-05-02 23:44:11,908 - distributed.nanny - INFO - Worker closed
2023-05-02 23:44:14,116 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.16.3.90:45045'. Reason: nanny-close-gracefully
2023-05-02 23:44:14,117 - distributed.dask_worker - INFO - End worker
