2023-04-17 10:06:49,918 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.94:45171'
2023-04-17 10:07:03,843 - distributed.worker - INFO -       Start worker at:    tcp://172.16.3.94:42757
2023-04-17 10:07:03,843 - distributed.worker - INFO -          Listening to:    tcp://172.16.3.94:42757
2023-04-17 10:07:03,843 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2023-04-17 10:07:03,843 - distributed.worker - INFO -          dashboard at:          172.16.3.94:45046
2023-04-17 10:07:03,843 - distributed.worker - INFO - Waiting to connect to:   tcp://172.16.3.167:46559
2023-04-17 10:07:03,843 - distributed.worker - INFO - -------------------------------------------------
2023-04-17 10:07:03,843 - distributed.worker - INFO -               Threads:                         36
2023-04-17 10:07:03,843 - distributed.worker - INFO -                Memory:                 178.81 GiB
2023-04-17 10:07:03,843 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-d3jeobk4
2023-04-17 10:07:03,844 - distributed.worker - INFO - -------------------------------------------------
2023-04-17 10:07:03,851 - distributed.worker - INFO -         Registered to:   tcp://172.16.3.167:46559
2023-04-17 10:07:03,851 - distributed.worker - INFO - -------------------------------------------------
2023-04-17 10:07:03,851 - distributed.core - INFO - Starting established connection to tcp://172.16.3.167:46559
/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/xarray/core/common.py:965: FutureWarning: 'base' in .resample() and in Grouper() is deprecated.
The new arguments that you should use are 'offset' or 'origin'.

>>> df.resample(freq="3s", base=2)

becomes:

>>> df.resample(freq="3s", offset="2s")

  grouper = pd.Grouper(
/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/xarray/core/common.py:965: FutureWarning: 'base' in .resample() and in Grouper() is deprecated.
The new arguments that you should use are 'offset' or 'origin'.

>>> df.resample(freq="3s", base=2)

becomes:

>>> df.resample(freq="3s", offset="2s")

  grouper = pd.Grouper(
/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/xarray/core/common.py:965: FutureWarning: 'base' in .resample() and in Grouper() is deprecated.
The new arguments that you should use are 'offset' or 'origin'.

>>> df.resample(freq="3s", base=2)

becomes:

>>> df.resample(freq="3s", offset="2s")

  grouper = pd.Grouper(
2023-04-17 10:11:52,752 - distributed.utils_perf - INFO - full garbage collection released 2.47 GiB from 110 reference cycles (threshold: 9.54 MiB)
2023-04-17 10:12:05,559 - distributed.utils_perf - INFO - full garbage collection released 0.95 GiB from 179 reference cycles (threshold: 9.54 MiB)
2023-04-17 10:13:11,310 - distributed.core - INFO - Event loop was unresponsive in Worker for 7.20s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-17 10:15:05,175 - distributed.utils_perf - INFO - full garbage collection released 1.75 GiB from 246 reference cycles (threshold: 9.54 MiB)
2023-04-17 10:15:23,717 - distributed.utils_perf - INFO - full garbage collection released 1.95 GiB from 194 reference cycles (threshold: 9.54 MiB)
2023-04-17 10:20:37,564 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/tornado/iostream.py", line 867, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/tornado/iostream.py", line 1140, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/worker.py", line 1215, in heartbeat
    response = await retry_operation(
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/utils_comm.py", line 386, in retry_operation
    return await retry(
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/utils_comm.py", line 371, in retry
    return await coro()
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/core.py", line 1163, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/core.py", line 928, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/.conda/envs/notebook_env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.16.3.94:40800 remote=tcp://172.16.3.167:46559>: ConnectionResetError: [Errno 104] Connection reset by peer
2023-04-17 10:20:37,567 - distributed.core - INFO - Connection to tcp://172.16.3.167:46559 has been closed.
2023-04-17 10:20:37,574 - distributed.worker - INFO - Stopping worker at tcp://172.16.3.94:42757. Reason: worker-handle-scheduler-connection-broken
2023-04-17 10:20:37,576 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.16.3.94:45171'. Reason: worker-handle-scheduler-connection-broken
2023-04-17 10:20:37,582 - distributed.nanny - INFO - Worker closed
2023-04-17 10:20:39,733 - distributed.nanny - ERROR - Worker process died unexpectedly
2023-04-17 10:20:41,152 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.16.3.94:45171'. Reason: nanny-close-gracefully
2023-04-17 10:20:41,152 - distributed.dask_worker - INFO - End worker
