2023-05-02 22:50:19,153 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.52:43780'
2023-05-02 22:50:22,261 - distributed.worker - INFO -       Start worker at:    tcp://172.16.3.52:32814
2023-05-02 22:50:22,261 - distributed.worker - INFO -          Listening to:    tcp://172.16.3.52:32814
2023-05-02 22:50:22,261 - distributed.worker - INFO -           Worker name:             SLURMCluster-7
2023-05-02 22:50:22,261 - distributed.worker - INFO -          dashboard at:          172.16.3.52:36933
2023-05-02 22:50:22,261 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.55:40487
2023-05-02 22:50:22,261 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 22:50:22,261 - distributed.worker - INFO -               Threads:                         36
2023-05-02 22:50:22,261 - distributed.worker - INFO -                Memory:                  93.13 GiB
2023-05-02 22:50:22,261 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-rr7islzk
2023-05-02 22:50:22,261 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 22:50:22,267 - distributed.worker - INFO -         Registered to:    tcp://172.16.3.55:40487
2023-05-02 22:50:22,267 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 22:50:22,267 - distributed.core - INFO - Starting established connection to tcp://172.16.3.55:40487
2023-05-02 22:51:20,588 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-05-02 22:51:21,271 - distributed.core - INFO - Removing comms to tcp://172.16.3.92:38986
2023-05-02 22:51:21,272 - distributed.core - INFO - Removing comms to tcp://172.16.3.85:40002
2023-05-02 22:51:21,276 - distributed.core - INFO - Removing comms to tcp://172.16.3.105:45260
2023-05-02 22:51:21,376 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 65.67 GiB -- Worker memory limit: 93.13 GiB
2023-05-02 22:51:23,750 - distributed.worker.memory - WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 74.90 GiB -- Worker memory limit: 93.13 GiB
2023-05-02 22:51:23,761 - distributed.core - INFO - Removing comms to tcp://172.16.3.83:41430
2023-05-02 22:51:29,287 - distributed.core - INFO - Removing comms to tcp://172.16.3.93:39445
2023-05-02 22:51:29,298 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.45s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-05-02 22:51:29,374 - distributed.core - INFO - Removing comms to tcp://172.16.3.63:44924
2023-05-02 22:51:29,468 - distributed.worker.memory - WARNING - Worker is at 79% memory usage. Resuming worker. Process memory: 74.23 GiB -- Worker memory limit: 93.13 GiB
2023-05-02 22:51:29,568 - distributed.worker.memory - WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 75.15 GiB -- Worker memory limit: 93.13 GiB
2023-05-02 22:51:31,513 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 81.41 GiB -- Worker memory limit: 93.13 GiB
2023-05-02 22:51:32,676 - distributed.nanny.memory - WARNING - Worker tcp://172.16.3.52:32814 (pid=270861) exceeded 95% memory budget. Restarting...
2023-05-02 22:51:40,293 - distributed.nanny - INFO - Worker process 270861 was killed by signal 15
2023-05-02 22:51:40,299 - distributed.nanny - WARNING - Restarting worker
2023-05-02 22:51:48,044 - distributed.worker - INFO -       Start worker at:    tcp://172.16.3.52:40984
2023-05-02 22:51:48,045 - distributed.worker - INFO -          Listening to:    tcp://172.16.3.52:40984
2023-05-02 22:51:48,045 - distributed.worker - INFO -           Worker name:             SLURMCluster-7
2023-05-02 22:51:48,045 - distributed.worker - INFO -          dashboard at:          172.16.3.52:44285
2023-05-02 22:51:48,046 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.55:40487
2023-05-02 22:51:48,046 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 22:51:48,046 - distributed.worker - INFO -               Threads:                         36
2023-05-02 22:51:48,046 - distributed.worker - INFO -                Memory:                  93.13 GiB
2023-05-02 22:51:48,046 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-rqhfgzmb
2023-05-02 22:51:48,046 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 22:51:48,054 - distributed.worker - INFO -         Registered to:    tcp://172.16.3.55:40487
2023-05-02 22:51:48,054 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 22:51:48,054 - distributed.core - INFO - Starting established connection to tcp://172.16.3.55:40487
2023-05-02 22:51:51,254 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-05-02 22:51:54,107 - distributed.core - INFO - Removing comms to tcp://172.16.3.92:41458
2023-05-02 22:51:55,138 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.85:35884
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2891, in get_data_from_worker
    response = await send_recv(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://172.16.3.52:43152 remote=tcp://172.16.3.85:35884>: ConnectionResetError: [Errno 104] Connection reset by peer
2023-05-02 22:51:55,284 - distributed.core - INFO - Removing comms to tcp://172.16.3.85:35884
2023-05-02 22:51:57,108 - distributed.core - INFO - Removing comms to tcp://172.16.3.105:46551
2023-05-02 22:51:59,307 - distributed.core - INFO - Removing comms to tcp://172.16.3.93:32854
2023-05-02 22:52:00,355 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.83:40074
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2891, in get_data_from_worker
    response = await send_recv(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://172.16.3.52:54953 remote=tcp://172.16.3.83:40074>: Stream is closed
2023-05-02 22:52:00,359 - distributed.core - INFO - Removing comms to tcp://172.16.3.83:40074
2023-05-02 22:52:10,145 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.03s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-05-02 22:52:20,171 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.24s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-05-02 22:52:23,357 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 65.95 GiB -- Worker memory limit: 93.13 GiB
2023-05-02 22:52:27,976 - distributed.worker.memory - WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 74.75 GiB -- Worker memory limit: 93.13 GiB
2023-05-02 22:52:33,675 - distributed.nanny.memory - WARNING - Worker tcp://172.16.3.52:40984 (pid=271041) exceeded 95% memory budget. Restarting...
2023-05-02 22:52:41,325 - distributed.nanny - INFO - Worker process 271041 was killed by signal 15
2023-05-02 22:52:41,327 - distributed.nanny - WARNING - Restarting worker
2023-05-02 22:52:46,078 - distributed.worker - INFO -       Start worker at:    tcp://172.16.3.52:40727
2023-05-02 22:52:46,080 - distributed.worker - INFO -          Listening to:    tcp://172.16.3.52:40727
2023-05-02 22:52:46,080 - distributed.worker - INFO -           Worker name:             SLURMCluster-7
2023-05-02 22:52:46,080 - distributed.worker - INFO -          dashboard at:          172.16.3.52:39887
2023-05-02 22:52:46,080 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.55:40487
2023-05-02 22:52:46,080 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 22:52:46,080 - distributed.worker - INFO -               Threads:                         36
2023-05-02 22:52:46,080 - distributed.worker - INFO -                Memory:                  93.13 GiB
2023-05-02 22:52:46,080 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-oaq4f53j
2023-05-02 22:52:46,081 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 22:52:46,088 - distributed.worker - INFO -         Registered to:    tcp://172.16.3.55:40487
2023-05-02 22:52:46,088 - distributed.worker - INFO - -------------------------------------------------
2023-05-02 22:52:46,089 - distributed.core - INFO - Starting established connection to tcp://172.16.3.55:40487
2023-05-02 22:56:57,556 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.49s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-05-02 22:57:10,862 - distributed.core - INFO - Removing comms to tcp://172.16.3.85:44210
2023-05-02 22:57:19,263 - distributed.core - INFO - Removing comms to tcp://172.16.3.83:45219
2023-05-02 22:57:26,060 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 64.00 GiB -- Worker memory limit: 93.13 GiB
2023-05-02 22:57:27,237 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.105:38846
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2891, in get_data_from_worker
    response = await send_recv(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://172.16.3.52:40288 remote=tcp://172.16.3.105:38846>: ConnectionResetError: [Errno 104] Connection reset by peer
2023-05-02 22:57:27,245 - distributed.core - INFO - Removing comms to tcp://172.16.3.105:38846
2023-05-02 22:57:28,233 - distributed.core - INFO - Removing comms to tcp://172.16.3.93:44738
2023-05-02 22:57:28,249 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.93:44738
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/core.py", line 329, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils.py", line 1850, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/asyncio/tasks.py", line 435, in wait_for
    return fut.result()
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://172.16.3.52:44501 remote=tcp://172.16.3.93:44738>: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2888, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1509, in connect
    return await connect_attempt
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1430, in _connect
    comm = await connect(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/core.py", line 334, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://172.16.3.93:44738 after 30 s
2023-05-02 22:57:31,607 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.53:35183
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/core.py", line 329, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils.py", line 1850, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://172.16.3.52:58756 remote=tcp://172.16.3.53:35183>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2888, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1509, in connect
    return await connect_attempt
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1430, in _connect
    comm = await connect(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/core.py", line 334, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://172.16.3.53:35183 after 30 s
2023-05-02 22:57:31,617 - distributed.core - INFO - Removing comms to tcp://172.16.3.53:35183
2023-05-02 22:57:32,848 - distributed.core - INFO - Removing comms to tcp://172.16.3.92:39919
2023-05-02 22:57:35,024 - distributed.utils_perf - INFO - full garbage collection released 327.06 MiB from 20 reference cycles (threshold: 9.54 MiB)
2023-05-02 22:57:35,026 - distributed.worker.memory - WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 74.61 GiB -- Worker memory limit: 93.13 GiB
2023-05-02 22:57:35,031 - distributed.worker - ERROR - Worker stream died during communication: tcp://172.16.3.63:41773
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 2891, in get_data_from_worker
    response = await send_recv(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1027, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://172.16.3.52:59265 remote=tcp://172.16.3.63:41773>: ConnectionResetError: [Errno 104] Connection reset by peer
2023-05-02 22:57:35,642 - distributed.core - INFO - Removing comms to tcp://172.16.3.63:41773
2023-05-02 22:57:36,097 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 80.49 GiB -- Worker memory limit: 93.13 GiB
2023-05-02 22:57:37,974 - distributed.nanny.memory - WARNING - Worker tcp://172.16.3.52:40727 (pid=271258) exceeded 95% memory budget. Restarting...
slurmstepd: error: *** JOB 3081849 ON pn002 CANCELLED AT 2023-05-02T22:57:41 ***
