2023-05-09 21:15:12,871 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.103:35382'
2023-05-09 21:15:15,246 - distributed.worker - INFO -       Start worker at:   tcp://172.16.3.103:40830
2023-05-09 21:15:15,247 - distributed.worker - INFO -          Listening to:   tcp://172.16.3.103:40830
2023-05-09 21:15:15,247 - distributed.worker - INFO -           Worker name:             SLURMCluster-6
2023-05-09 21:15:15,247 - distributed.worker - INFO -          dashboard at:         172.16.3.103:46432
2023-05-09 21:15:15,247 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.56:38364
2023-05-09 21:15:15,247 - distributed.worker - INFO - -------------------------------------------------
2023-05-09 21:15:15,247 - distributed.worker - INFO -               Threads:                         36
2023-05-09 21:15:15,247 - distributed.worker - INFO -                Memory:                  93.13 GiB
2023-05-09 21:15:15,247 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-o0j4mpb_
2023-05-09 21:15:15,247 - distributed.worker - INFO - -------------------------------------------------
2023-05-09 21:15:15,255 - distributed.worker - INFO -         Registered to:    tcp://172.16.3.56:38364
2023-05-09 21:15:15,255 - distributed.worker - INFO - -------------------------------------------------
2023-05-09 21:15:15,256 - distributed.core - INFO - Starting established connection to tcp://172.16.3.56:38364
HDF5-DIAG: Error detected in HDF5 (1.14.0) thread 1:
  #000: H5D.c line 1390 in H5Dwrite(): can't synchronously write data
    major: Dataset
    minor: Write failed
  #001: H5D.c line 1333 in H5D__write_api_common(): can't write data
    major: Dataset
    minor: Write failed
  #002: H5VLcallback.c line 2282 in H5VL_dataset_write_direct(): dataset write failed
    major: Virtual Object Layer
    minor: Write failed
  #003: H5VLcallback.c line 2237 in H5VL__dataset_write(): dataset write failed
    major: Virtual Object Layer
    minor: Write failed
  #004: H5VLnative_dataset.c line 408 in H5VL__native_dataset_write(): can't write data
    major: Dataset
    minor: Write failed
  #005: H5Dio.c line 648 in H5D__write(): unable to initialize storage
    major: Dataset
    minor: Unable to initialize object
  #006: H5Dint.c line 2346 in H5D__alloc_storage(): unable to initialize dataset with fill value
    major: Dataset
    minor: Unable to initialize object
  #007: H5Dint.c line 2404 in H5D__init_storage(): unable to allocate all chunks of dataset
    major: Dataset
    minor: Unable to initialize object
  #008: H5Dcontig.c line 312 in H5D__contig_fill(): unable to write fill value to dataset
    major: Dataset
    minor: Unable to initialize object
  #009: H5Dcontig.c line 958 in H5D__contig_write_one(): vector write failed
    major: Low-level I/O
    minor: Write failed
  #010: H5Dcontig.c line 1530 in H5D__contig_writevv(): can't perform vectorized sieve buffer write
    major: Dataset
    minor: Can't operate on object
  #011: H5VM.c line 1400 in H5VM_opvv(): can't perform operation
    major: Internal error (too specific to document in detail)
    minor: Can't operate on object
  #012: H5Dcontig.c line 1283 in H5D__contig_writevv_sieve_cb(): block write failed
    major: Dataset
    minor: Write failed
  #013: H5Fio.c line 190 in H5F_shared_block_write(): write through page buffer failed
    major: Low-level I/O
    minor: Write failed
  #014: H5PB.c line 1017 in H5PB_write(): write through metadata accumulator failed
    major: Page Buffering
    minor: Write failed
  #015: H5Faccum.c line 832 in H5F__accum_write(): file write failed
    major: Low-level I/O
    minor: Write failed
  #016: H5FDint.c line 306 in H5FD_write(): driver write request failed
    major: Virtual File Layer
    minor: Write failed
    major: Low-level I/O
    minor: Write failed
HDF5-DIAG: Error detected in HDF5 (1.14.0) thread 2:
    major: Dataset
    major: Dataset
2023-05-09 21:16:48,335 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-703489acd73f3c302eb2ca88b2a9dde6', 0, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-4a17df1f-189d-41ca-a889-7c4509ff63ed, array([[[  28.8570147 ,   28.55367437,   28.14467416, ...,
            3.47360822,    3.49956544,    3.50463172],
        [  25.33469878,   25.1940714 ,   26.53143836, ...,
            3.41251403,    3.44482438,    3.45991252],
        [  25.39893333,   26.96943424,   29.26106449, ...,
            3.35528578,    3.39651669,    3.43388213],
        ...,
        [  -5.27923953,   -4.83415061,   -4.41556432, ...,
         -195.87574022, -193.6007896 , -191.9999466 ],
        [  -6.87026096,   -6.42252191,   -6.06723277, ...,
         -196.80362994, -193.94594698, -192.71324652],
        [  -8.5810746 ,   -8.11974064,   -7.75917127, ...,
         -197.02767576, -194.34535704, -194.03037639]],

       [[  28.87931494,   28.57056022,   28.15478095, ...,
            3.14386712,    3.17127772,    3.17834972],
        [  25.3546433 ,   25.20475187,   26.5241066 , ...,
            3.09356288,    
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:16:48,349 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-0c319ee7382323b9b5e98011ffe419d1', 0, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-111e63ed-9382-4940-b350-3817b415c134, array([[[ -19.98618362,  -22.14093038,  -25.68515918, ...,
            6.68738636,    6.56001165,    6.4298823 ],
        [ -28.94004653,  -31.77714792,  -35.54201573, ...,
            7.12617195,    7.01627326,    6.88870151],
        [ -37.35121453,  -37.42327068,  -35.96091613, ...,
            7.57405453,    7.4730502 ,    7.36875144],
        ...,
        [-242.89224491, -243.40035557, -243.93217838, ...,
         -155.81938121, -156.96652082, -157.86438447],
        [-240.42614839, -240.97640943, -241.58383462, ...,
         -147.54161957, -148.60328996, -149.97434396],
        [-238.16383223, -238.75482803, -239.3622248 , ...,
         -138.40970115, -139.59026588, -142.77565075]],

       [[ -19.78280199,  -21.92325763,  -25.45276344, ...,
            6.68526014,    6.56389632,    6.44002011],
        [ -28.74894918,  -31.57603817,  -35.3446509 , ...,
            7.11405843,    
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:18:17,602 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-061c5f946151b13c3dcb68688a3c683f', 0, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-11a1cbe1-3457-4430-a86e-ec87d5db4dde, array([[[ -19.98618362,  -22.14093038,  -25.68515918, ...,
            6.68738636,    6.56001165,    6.4298823 ],
        [ -28.94004653,  -31.77714792,  -35.54201573, ...,
            7.12617195,    7.01627326,    6.88870151],
        [ -37.35121453,  -37.42327068,  -35.96091613, ...,
            7.57405453,    7.4730502 ,    7.36875144],
        ...,
        [-242.89224491, -243.40035557, -243.93217838, ...,
         -155.81938121, -156.96652082, -157.86438447],
        [-240.42614839, -240.97640943, -241.58383462, ...,
         -147.54161957, -148.60328996, -149.97434396],
        [-238.16383223, -238.75482803, -239.3622248 , ...,
         -138.40970115, -139.59026588, -142.77565075]],

       [[ -19.78280199,  -21.92325763,  -25.45276344, ...,
            6.68526014,    6.56389632,    6.44002011],
        [ -28.74894918,  -31.57603817,  -35.3446509 , ...,
            7.11405843,    
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:18:23,942 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-0c29a489a33ab6187045d5727e115ba0', 13, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-89392ee9-8d84-4d37-96f1-0043bf8098ad, array([[[  20.54957362,   19.88939226,   18.89253019, ...,
            2.55756338,    2.51061795,    2.44205317],
        [  15.69859085,   15.04019018,   15.62705059, ...,
            2.49615764,    2.46436182,    2.40590002],
        [  13.66512389,   14.90051395,   17.14045394, ...,
            2.4106735 ,    2.40194616,    2.377121  ],
        ...,
        [ -22.65699746,  -22.05502591,  -21.42020363, ...,
          -39.67958736,  -39.16550482,  -39.58322039],
        [ -22.68771548,  -22.08872524,  -21.48747989, ...,
          -39.30196137,  -39.24607788,  -40.31046407],
        [ -22.71955466,  -22.1258421 ,  -21.52096968, ...,
          -38.99425594,  -39.29056854,  -41.62523463]],

       [[  20.82675674,   20.14977839,   19.13009711, ...,
            2.62319521,    2.57878864,    2.51288776],
        [  15.9070105 ,   15.22915025,   15.81063642, ...,
            2.55662071,    
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:18:24,563 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-0c29a489a33ab6187045d5727e115ba0', 16, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-89392ee9-8d84-4d37-96f1-0043bf8098ad, array([[[  25.48054955,   25.30224681,   25.09269878, ...,
            9.69778169,    9.77272617,    9.79280271],
        [  22.58412885,   22.60067096,   23.76135168, ...,
            9.88372709,    9.98814794,   10.03393495],
        [  22.97898984,   24.42004059,   26.1435207 , ...,
           10.06959179,   10.20582386,   10.30680786],
        ...,
        [   8.29891772,    8.58259873,    8.87425721, ...,
         -171.24737689, -168.97739965, -166.77078061],
        [   6.67415438,    6.9548579 ,    7.18485127, ...,
         -169.77115327, -167.14901992, -165.34138813],
        [   4.99580175,    5.28067665,    5.51125235, ...,
         -167.78171968, -165.35604243, -164.59136681]],

       [[  25.77751876,   25.62766933,   25.45140877, ...,
            9.60648704,    9.67964157,    9.69898841],
        [  22.95368606,   23.00256711,   24.20248565, ...,
            9.7863718 ,    
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:18:25,274 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-0c29a489a33ab6187045d5727e115ba0', 19, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-89392ee9-8d84-4d37-96f1-0043bf8098ad, array([[[18.42046657, 17.00138895, 14.97308433, ...,  2.13306591,
          2.32788976,  2.43226948],
        [12.02823425, 10.60556027, 10.50078522, ...,  1.71634736,
          1.96608283,  2.12639056],
        [10.13916901, 11.59046349, 13.88533519, ...,  1.24063701,
          1.62007056,  1.93596324],
        ...,
        [33.80773009, 34.30980974, 34.82288122, ..., 15.62067343,
         17.4814779 , 18.27684991],
        [33.18430847, 33.66700025, 34.11249306, ..., 13.87260618,
         14.5014912 , 14.62385589],
        [32.52666792, 33.00705259, 33.4510431 , ..., 11.1665717 ,
         11.46997754, 11.01012221]],

       [[19.24550998, 17.82740723, 15.80361231, ...,  2.86368516,
          3.06651855,  3.17316765],
        [12.75669697, 11.3430181 , 11.27971275, ...,  2.4384131 ,
          2.69460786,  2.85687896],
        [10.83606799, 12.32421762, 14.67647978, ...,  1.95060751,
  
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:18:25,840 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-0c29a489a33ab6187045d5727e115ba0', 2, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-89392ee9-8d84-4d37-96f1-0043bf8098ad, array([[[25.90416519, 25.18467208, 24.39357429, ..., 19.12610102,
         18.83194708, 18.56530232],
        [20.28623929, 19.94431581, 21.24980089, ..., 19.12651836,
         18.84876412, 18.60943901],
        [19.60862248, 21.88278068, 24.47160523, ..., 19.23577231,
         19.01628888, 18.83275926],
        ...,
        [42.62194412, 43.01562981, 43.37878674, ..., 22.08846218,
         23.71535773, 24.17362992],
        [41.59085166, 41.97830833, 42.33711862, ..., 19.9233781 ,
         20.14705034, 19.82886919],
        [40.50970095, 40.93844692, 41.3001642 , ..., 16.62328526,
         16.51178823, 15.43369224]],

       [[25.60861516, 24.90541061, 24.12050943, ..., 18.87970043,
         18.57574768, 18.29997304],
        [19.98037186, 19.64516832, 20.9377338 , ..., 18.87324936,
         18.58979368, 18.34206181],
        [19.24996781, 21.50777756, 24.08694185, ..., 18.97486425,
  
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:18:26,226 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-0c29a489a33ab6187045d5727e115ba0', 21, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-89392ee9-8d84-4d37-96f1-0043bf8098ad, array([[[  21.54682646,   20.82574237,   19.74354794, ...,
            3.0352604 ,    3.00452028,    2.9524669 ],
        [  16.43351636,   15.70124701,   16.26192242, ...,
            2.96333108,    2.95067271,    2.90991295],
        [  14.23991296,   15.48341082,   17.8195253 , ...,
            2.86949898,    2.88435922,    2.88204083],
        ...,
        [ -19.87591322,  -19.23396527,  -18.58256897, ...,
          -25.16746999,  -25.0819711 ,  -25.90097759],
        [ -19.79843848,  -19.15766816,  -18.53126822, ...,
          -24.70254542,  -25.23799529,  -26.73548113],
        [ -19.72231695,  -19.08237482,  -18.45394443, ...,
          -24.50335571,  -25.40076027,  -28.15192365]],

       [[  21.74340273,   21.00992557,   19.90933936, ...,
            3.25721408,    3.23294694,    3.18730863],
        [  16.57087477,   15.82231301,   16.37508618, ...,
            3.1872428 ,    
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:18:26,684 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-0c29a489a33ab6187045d5727e115ba0', 23, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-89392ee9-8d84-4d37-96f1-0043bf8098ad, array([[[  28.81474516,   28.4800236 ,   28.01088989, ...,
            0.8632166 ,    0.88974672,    0.90205346],
        [  25.14671865,   24.91984383,   26.07894708, ...,
            0.89280514,    0.92939517,    0.95068579],
        [  24.85113203,   26.24493039,   28.3899918 , ...,
            0.92543552,    0.97396081,    1.01634206],
        ...,
        [ -11.20346396,  -10.70754844,  -10.24321606, ...,
         -183.5414828 , -182.17660351, -181.52889842],
        [ -12.75744917,  -12.26380024,  -11.85693033, ...,
         -184.69830757, -182.80706062, -182.50699977],
        [ -14.37413046,  -13.88612817,  -13.47561369, ...,
         -185.21763626, -183.50592803, -184.11127234]],

       [[  28.80134521,   28.46720408,   27.99371569, ...,
            0.64787938,    0.67287212,    0.68455377],
        [  25.10256767,   24.86869191,   26.01158445, ...,
            0.68493141,    
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:19:40,561 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-4e8d1c8f23b5b003377a08fb0d4216ea', 10, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-fce1195b-1037-49db-bff8-520761473ff4, array([[[ 8.52154792e-01, -1.63520266e+00, -6.17389165e+00, ...,
          6.92994910e+01,  6.91090835e+01,  6.89078985e+01],
        [-5.72686062e+00, -8.62199199e+00, -1.23446140e+01, ...,
          7.14834718e+01,  7.15303686e+01,  7.14045665e+01],
        [-9.22162054e+00, -9.39315167e+00, -7.89274736e+00, ...,
          7.42059100e+01,  7.43222375e+01,  7.43709554e+01],
        ...,
        [-2.48102599e+02, -2.47898836e+02, -2.47706889e+02, ...,
         -1.49973930e+02, -1.53262365e+02, -1.57336090e+02],
        [-2.47502061e+02, -2.47310849e+02, -2.47141417e+02, ...,
         -1.52368887e+02, -1.56257584e+02, -1.61184709e+02],
        [-2.46832409e+02, -2.46620891e+02, -2.46448031e+02, ...,
         -1.52970470e+02, -1.57005148e+02, -1.62973570e+02]],

       [[ 4.66768979e-01, -2.04062042e+00, -6.59440610e+00, ...,
          7.00292765e+01,  6.98359165e+01,  6.96335036e+01],
  
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:20:04,922 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-e310234f183540149c6a3b3b221e6392', 20, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-4c38fc26-3316-490e-8c73-3dfcfc5174bd, array([[[  23.30854475,   22.22911177,   20.36973355, ...,
            8.56213798,    8.8206554 ,    8.99712714],
        [  16.68607984,   15.5017394 ,   15.77363374, ...,
            7.99925981,    8.28750893,    8.50257357],
        [  14.20092944,   15.79969212,   18.73284944, ...,
            7.42272368,    7.76555379,    8.06145679],
        ...,
        [  12.59329628,   12.94496902,   13.38748684, ...,
           16.93720433,   18.58104809,   18.86977704],
        [  12.18713223,   12.51165044,   12.85283308, ...,
           16.11945818,   16.6660062 ,   16.24843307],
        [  11.80148511,   12.1177229 ,   12.46032803, ...,
           14.40828519,   14.58546813,   13.34998577]],

       [[  23.37192635,   22.28355565,   20.4079365 , ...,
            7.8968281 ,    8.16612396,    8.35470295],
        [  16.67527452,   15.47401006,   15.74146023, ...,
            7.3192566 ,    
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:20:05,220 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-e310234f183540149c6a3b3b221e6392', 3, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-4c38fc26-3316-490e-8c73-3dfcfc5174bd, array([[[ 1.50620049e+01,  1.36578703e+01,  1.16460134e+01, ...,
         -9.07722520e-01, -7.43188831e-01, -6.37994349e-01],
        [ 9.22216001e+00,  7.78459409e+00,  7.52777538e+00, ...,
         -1.19942143e+00, -9.80881074e-01, -8.21517299e-01],
        [ 7.59446170e+00,  8.87712041e+00,  1.08982032e+01, ...,
         -1.51607655e+00, -1.18385293e+00, -8.80893474e-01],
        ...,
        [ 3.26802501e+01,  3.31658616e+01,  3.36581790e+01, ...,
          1.22522223e+01,  1.40557001e+01,  1.48305162e+01],
        [ 3.20841916e+01,  3.25499767e+01,  3.29718124e+01, ...,
          1.05266554e+01,  1.11717653e+01,  1.12897714e+01],
        [ 3.14712654e+01,  3.19283563e+01,  3.23476771e+01, ...,
          7.94105859e+00,  8.26522447e+00,  7.81662691e+00]],

       [[ 1.54119095e+01,  1.40029735e+01,  1.19841527e+01, ...,
         -5.81862242e-01, -4.15572006e-01, -3.13120403e-01],
  
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:20:05,524 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-e310234f183540149c6a3b3b221e6392', 7, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-4c38fc26-3316-490e-8c73-3dfcfc5174bd, array([[[  28.89598572,   28.57719619,   28.14717389, ...,
            2.50127804,    2.53055936,    2.54076254],
        [  25.35632824,   25.18663046,   26.46645777, ...,
            2.47286563,    2.50969998,    2.52944598],
        [  25.3463362 ,   26.85126538,   29.07599828, ...,
            2.44732278,    2.4938313 ,    2.53519541],
        ...,
        [  -7.23554399,   -6.77513002,   -6.34650519, ...,
         -192.79590079, -190.82853352, -189.53750432],
        [  -8.81023473,   -8.34888537,   -7.98333274, ...,
         -193.82651717, -191.28485566, -190.35194311],
        [ -10.49210675,  -10.02443038,   -9.65398539, ...,
         -194.17364363, -191.80620606, -191.78121465]],

       [[  28.89219873,   28.56898702,   28.13170381, ...,
            2.19335388,    2.22303505,    2.23434393],
        [  25.33956204,   25.15960939,   26.41856666, ...,
            2.17572705,    
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:20:05,827 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-e310234f183540149c6a3b3b221e6392', 9, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-4c38fc26-3316-490e-8c73-3dfcfc5174bd, array([[[ 39.49782403,  39.05314859,  38.65258979, ...,  21.57894374,
          21.44142146,  21.2324545 ],
        [ 34.82205112,  34.68861473,  36.38788232, ...,  21.93175176,
          21.83669412,  21.66125569],
        [ 35.05439359,  37.2808194 ,  40.1826253 , ...,  22.31935261,
          22.28126775,  22.18349258],
        ...,
        [ 33.33927938,  33.66244402,  33.95793841, ..., -34.47454594,
         -32.32633214, -31.25249266],
        [ 32.08131046,  32.40907522,  32.70381969, ..., -35.3003222 ,
         -33.90539692, -33.60862332],
        [ 30.76952066,  31.13322981,  31.429264  , ..., -36.43778584,
         -35.41267241, -36.59915019]],

       [[ 38.80408087,  38.35607865,  37.92447983, ...,  22.05859757,
          21.91278218,  21.69455932],
        [ 34.14878846,  33.99116073,  35.61638042, ...,  22.39617919,
          22.29164341,  22.10758331],
        [ 34.3092024
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:20:06,129 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-1a986644c250c60cb0293034fe52b71e', 11, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-32623e93-eca0-4775-8b18-98720bca2597, array([[[ -25.93197218,  -28.11806702,  -32.60742086, ...,
           29.11167871,   28.89287495,   28.70036259],
        [ -36.53271089,  -39.29736023,  -42.80275657, ...,
           30.68327749,   30.55330748,   30.37579793],
        [ -45.99562826,  -46.00557758,  -43.86865417, ...,
           32.60536153,   32.52604713,   32.44091771],
        ...,
        [-275.9780451 , -275.61548743, -275.30195698, ...,
         -173.14596395, -176.79638574, -181.11612909],
        [-276.06425473, -275.71380865, -275.38908023, ...,
         -174.86598303, -179.10481992, -184.25444083],
        [-275.97585312, -275.63745733, -275.31364483, ...,
         -175.24458433, -179.58156824, -185.47359842]],

       [[ -25.76680081,  -27.99895075,  -32.54862063, ...,
           28.96882954,   28.74238917,   28.54316464],
        [ -36.44815399,  -39.27160637,  -42.85802099, ...,
           30.54641135,   3
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:20:06,434 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-1a986644c250c60cb0293034fe52b71e', 12, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-32623e93-eca0-4775-8b18-98720bca2597, array([[[ -32.29765047,  -34.64464465,  -38.92103519, ...,
           19.07611046,   18.76909949,   18.47890623],
        [ -44.58633041,  -47.77301169,  -51.79156621, ...,
           20.39736445,   20.14301549,   19.85795661],
        [ -56.59638056,  -56.67729365,  -54.58600733, ...,
           21.76770432,   21.56108545,   21.34835225],
        ...,
        [-255.68559441, -255.53009222, -255.40914774, ...,
         -144.85535417, -147.74783358, -151.27280326],
        [-256.69119623, -256.57195114, -256.53745116, ...,
         -146.72074969, -150.19452129, -154.57170456],
        [-257.82778838, -257.75750249, -257.72420549, ...,
         -147.64509042, -151.25704796, -156.96372646]],

       [[ -33.26896997,  -35.63805729,  -39.96258693, ...,
           19.68000758,   19.35969626,   19.05607956],
        [ -45.76022351,  -48.97626695,  -53.02635138, ...,
           20.99646001,   2
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:20:06,754 - distributed.worker - WARNING - Compute Failed
Key:       ('sub-store-map-1a986644c250c60cb0293034fe52b71e', 14, 0, 0)
Function:  execute_task
args:      ((<function store_chunk at 0x2aaad7655870>, (subgraph_callable-32623e93-eca0-4775-8b18-98720bca2597, array([[[ -10.15632638,  -11.94614973,  -14.89167426, ...,
            7.22970091,    7.15396149,    7.07833613],
        [ -17.01836119,  -19.33865683,  -22.44700117, ...,
            7.53363942,    7.46865155,    7.39468378],
        [ -23.32332056,  -23.23679522,  -21.83413501, ...,
            7.82835316,    7.77178614,    7.71365014],
        ...,
        [-293.80463818, -294.23391115, -294.65292794, ...,
         -146.74782482, -149.44712294, -151.93510677],
        [-291.35409696, -291.83666639, -292.36751022, ...,
         -141.65173686, -144.15809235, -147.1349751 ],
        [-288.77497915, -289.33433188, -289.86709415, ...,
         -135.61533726, -138.22607765, -142.70916842]],

       [[  -9.72419331,  -11.48182558,  -14.38144733, ...,
            7.29117756,    7.2149986 ,    7.13911621],
        [ -16.45478266,  -18.73423808,  -21.78808009, ...,
            7.59253394,    
kwargs:    {}
Exception: "RuntimeError('NetCDF: HDF error')"

--- Logging error ---
2023-05-09 21:36:45,993 - distributed.core - INFO - Connection to tcp://172.16.3.56:38364 has been closed.
2023-05-09 21:36:45,995 - distributed.worker - INFO - Stopping worker at tcp://172.16.3.103:40830. Reason: worker-handle-scheduler-connection-broken
2023-05-09 21:36:45,998 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.16.3.103:35382'. Reason: worker-handle-scheduler-connection-broken
2023-05-09 21:36:48,109 - distributed.client - ERROR - 
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/core.py", line 292, in connect
    comm = await wait_for(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 511, in connect
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x2aab52047130>: ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/client.py", line 1323, in _reconnect
    await self._ensure_connected(timeout=timeout)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/client.py", line 1353, in _ensure_connected
    comm = await connect(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/core.py", line 316, in connect
    await asyncio.sleep(backoff)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError
2023-05-09 21:36:48,134 - distributed.nanny - INFO - Worker closed
2023-05-09 21:36:50,137 - distributed.nanny - ERROR - Worker process died unexpectedly
2023-05-09 21:36:50,471 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.16.3.103:35382'. Reason: nanny-close-gracefully
2023-05-09 21:36:50,472 - distributed.dask_worker - INFO - End worker
